name: /home/hyang/deadclip/CyCLIP/env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - blosc=1.21.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.2.2
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf5=1.12.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - lzo=2.10
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - numexpr=2.8.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.6
  - python-dateutil=2.8.2
  - pytorch-mutex=1.0
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - tornado=6.2
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - tzdata=2022e
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - albumentations==1.3.0
    - aniso8601==9.0.1
    - antlr4-python3-runtime==4.9.3
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autofaiss==2.15.3
    - av==10.0.0
    - braceexpand==0.1.7
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - clip==1.0
    - clip-anytorch==2.5.0
    - clip-retrieval==2.35.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - dataclasses==0.6
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - einops==0.5.0
    - embedding-reader==1.5.0
    - exifread-nocycle==3.0.1
    - faiss-cpu==1.7.3
    - filelock==3.8.0
    - fire==0.4.0
    - flask==2.2.2
    - flask-cors==3.0.10
    - flask-restful==0.3.9
    - flatbuffers==22.9.24
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.1.0
    - ftfy==6.1.1
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.10.1
    - humanize==4.4.0
    - hydra-core==1.3.0
    - imageio==2.22.2
    - img2dataset==1.35.0
    - imutils==0.5.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - kaggle==1.5.12
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - lightly==1.2.39
    - lightly-utils==0.0.2
    - littleutils==0.2.2
    - llvmlite==0.42.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - mpmath==1.3.0
    - multidict==6.0.2
    - multilingual-clip==1.0.10
    - networkx==2.8.7
    - nltk==3.7
    - numba==0.59.1
    - numpy==1.23.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==11.515.75
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - nvitop==0.11.0
    - oauthlib==3.2.2
    - ogb==1.3.6
    - omegaconf==2.2.3
    - open-clip-torch==2.0.2
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - opt-einsum==3.3.0
    - outdated==0.2.2
    - pandas==1.5.1
    - pathtools==0.1.2
    - pillow==9.2.0
    - pip==22.3.1
    - prometheus-client==0.15.0
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.3
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pydeprecate==0.3.2
    - pyflakes==2.5.0
    - pynndescent==0.5.12
    - python-magic==0.4.27
    - python-slugify==7.0.0
    - pytorch-lightning==1.7.7
    - pytz==2022.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.3
    - seaborn==0.12.1
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.10.0
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - sympy==1.12.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tokenizers==0.13.1
    - torch==2.3.1
    - torchmetrics==0.10.0
    - torchvision==0.13.1
    - tqdm==4.64.1
    - transformers==4.23.1
    - triton==2.3.1
    - typing-extensions==4.12.1
    - umap-learn==0.5.6
    - visual-genome==1.0.0
    - wandb==0.12.21
    - webdataset==0.1.103
    - werkzeug==2.2.2
    - wget==3.2
    - wilds==2.0.0
    - wrapt==1.14.1
    - yarl==1.8.1
prefix: /home/hyang/deadclip/CyCLIP/env
